### ISSUE TITLE
Want to include a non-fastlane xcode-version?

### ISSUE THREAD

**Issue by klaaspieter** [ios-factor/ios-factor.com#28]
I'm a big fan of having a .xcode-version (or .tools-version for asdf users), but I want it to work with or without fastlane.

I'm the author of [chxcode](https://github.com/klaaspieter/chxcode) which can automatically change the current Xcode for the current directory based on the presence of `.xcode-version`. It's mostly written POSIX sh compatible and supports bash and zsh. 

Is this something y'all would consider including?

**Comment by KrauseFx** [comment]
Hey this is great! Do a lot of people use chxcode? Did your tool already use `.xcode-version` or was that something you recently added? This is great, do you want to submit a PR to add a link to it?

**Comment by klaaspieter** [comment]
As far as I know I'm the only one using it at the moment. I built it specifically for use with `.xcode-version`. It was inspired by `chruby` and similar tools for other languages.

I'll add a link.

**Comment by KrauseFx** [comment]
Awesome
