### ISSUE TITLE
Understanding Veertu

### ISSUE THREAD

**Issue by jaydrogers** [ios-factor/ios-factor.com#33]
Thanks a ton for putting this all together, this is an **amazing resource** and super helpful. One thing that I had a question on was regarding [Veertu](https://veertu.com/).

There is a mention of it here: https://github.com/ios-factor/ios-factor.com/blame/master/_i18n/en/factors/deployment.md#L11

Upon reading this line, I got super excited of a possible open source solution where we could run our own Mac OS X build servers on Digital Ocean or something similar. At first glance it looks like it is a commercial product only (understandable that developers need to eat too). Doing some additional research, it looks like they may have had a solution back in the day that was on the "open source with commercial support" model, but I couldn't find that on their current website.

**Few questions & suggestions:**

1. Does Veertu have an open source version? If so, maybe provide a better link explaining the different options between open source and commercial support.
1. Is Veertu a commercial product only? If so, maybe make that clear on Line 11. You might want to also clear up if they are a sponsor or not (some people get salty & hesitant with commercial referrals).
1. Does Veertu require Mac OS X hardware? If so, then maybe emphasizing that again will make it clear to the reader.

Looking forward to hearing your thoughts and any other suggestions.

**Comment by KrauseFx** [comment]
Thanks for submitting this issue, those are some really good questions. I haven't actually used Veertu myself, and I don't know enough about their strategy, I'll ping my friend who's more familiar, maybe he can help answer those questions :)

**Comment by medicis123** [comment]
Hi, From Veertu  - The product to containerize macOS and use it for iOS DevOps is Anka Build product from Veertu. It's not opensource.  Only available as a commercial product. Anka Build only runs on mac hardware to build macOS cloud and run macOS instances because that's the legal way to set things up.
Veertu had a product called VDHH (Veertu Desktop) which was macOS virtualization to run only Windows and Linux VMs. It doesn't do macOS VMs on macOS. Hope this helps.

**Comment by jaydrogers** [comment]
Thanks for the information. I created a pull request to clarify that paragraph. Thanks again for putting this all together!

**Comment by KrauseFx** [comment]
Perfect, moved over to https://github.com/ios-factor/ios-factor.com/pull/34, thanks y'all
