### ISSUE TITLE
CFBundleVersion follows semver?

### ISSUE THREAD

**Issue by kiliankoe** [ios-factor/ios-factor.com#36]
Hi!

Just a quick question regarding the following wording on the versioning page.

> Build number (CFBundleVersion) - shown as Build in Xcode: an incrementing number following semver

Is it really considered good practice to use semver for the CFBundleVersion? In my experience this is usually an integer that's incremented in arbitrary intervals (based on builds or commits or whatever). Using semver for the CFBundleShortVersionString seems like a more sensible choice.

The rest of the page reads as though it's meant that way as well, I just stumbled across the mention of semver at that point.

If it's not meant that way I can gladly submit a PR and try to word that section a bit differently 😊

**Comment by KrauseFx** [comment]
Actually yah, somebody told me that the official docs mention this, I just added it https://github.com/ios-factor/ios-factor.com/commit/251404cb12701e02ef6b2c88680c9d07807a8dde

You're right though, it doesn't seem like a lot of people do it, so I'll revert the commit

**Comment by KrauseFx** [comment]
Done https://github.com/ios-factor/ios-factor.com/commit/0f5991134aad42d27ee7fd63d1d815d1cd51004b 👍 Thanks for the issue

**Comment by benoittgt** [comment]
Why it has been reverted?
